package Entity;
// Generated Mar 22, 2024, 9:28:17 AM by Hibernate Tools 5.6.15.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	private Integer idAccount;
	private Serializable firstName;
	private Serializable lastName;
	private Serializable userName;
	private Serializable password;
	private Set carts = new HashSet(0);
	private Set wishlists = new HashSet(0);

	public Account() {
		
	}

	public Account(Serializable firstName, Serializable lastName, Serializable userName, Serializable password,
			Set carts, Set wishlists) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.userName = userName;
		this.password = password;
		this.carts = carts;
		this.wishlists = wishlists;
	}

	public Integer getIdAccount() {
		return this.idAccount;
	}

	public void setIdAccount(Integer idAccount) {
		this.idAccount = idAccount;
	}

	public Serializable getFirstName() {
		return this.firstName;
	}

	public void setFirstName(Serializable firstName) {
		this.firstName = firstName;
	}

	public Serializable getLastName() {
		return this.lastName;
	}

	public void setLastName(Serializable lastName) {
		this.lastName = lastName;
	}

	public Serializable getUserName() {
		return this.userName;
	}

	public void setUserName(Serializable userName) {
		this.userName = userName;
	}

	public Serializable getPassword() {
		return this.password;
	}

	public void setPassword(Serializable password) {
		this.password = password;
	}

	public Set getCarts() {
		return this.carts;
	}

	public void setCarts(Set carts) {
		this.carts = carts;
	}

	public Set getWishlists() {
		return this.wishlists;
	}

	public void setWishlists(Set wishlists) {
		this.wishlists = wishlists;
	}

}
