package Entity;
// Generated Mar 22, 2024, 9:28:17 AM by Hibernate Tools 5.6.15.Final

/**
 * Cart generated by hbm2java
 */
public class Cart implements java.io.Serializable {

	private Integer idCart;
	private Account account;
	private Integer idProduct;
	private Integer quantitty;

	public Cart() {
	}

	public Cart(Account account, Integer idProduct, Integer quantitty) {
		this.account = account;
		this.idProduct = idProduct;
		this.quantitty = quantitty;
	}

	public Integer getIdCart() {
		return this.idCart;
	}

	public void setIdCart(Integer idCart) {
		this.idCart = idCart;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Integer getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(Integer idProduct) {
		this.idProduct = idProduct;
	}

	public Integer getQuantitty() {
		return this.quantitty;
	}

	public void setQuantitty(Integer quantitty) {
		this.quantitty = quantitty;
	}

}
