package Entity;
// Generated Mar 22, 2024, 9:28:17 AM by Hibernate Tools 5.6.15.Final

/**
 * OrderProduct generated by hbm2java
 */
public class OrderProduct implements java.io.Serializable {

	private Integer idOrder;
	private Integer idAccount;
	private Integer idProduct;
	private Integer quantity;

	public OrderProduct() {
	}

	public OrderProduct(Integer idAccount, Integer idProduct, Integer quantity) {
		this.idAccount = idAccount;
		this.idProduct = idProduct;
		this.quantity = quantity;
	}

	public Integer getIdOrder() {
		return this.idOrder;
	}

	public void setIdOrder(Integer idOrder) {
		this.idOrder = idOrder;
	}

	public Integer getIdAccount() {
		return this.idAccount;
	}

	public void setIdAccount(Integer idAccount) {
		this.idAccount = idAccount;
	}

	public Integer getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(Integer idProduct) {
		this.idProduct = idProduct;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

}
