package Entity;
// Generated Mar 22, 2024, 9:28:17 AM by Hibernate Tools 5.6.15.Final

import java.io.Serializable;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import java.util.Date;

/**
 * Product generated by hbm2java
 */

@Entity
@Table(name="Product")
public class Product implements java.io.Serializable {
	@Id
	@Basic
	@Column(name="id_product")
	private Integer idProduct;
	@Column(name="nameProduct")
	private Serializable nameProduct;
	@Column(name="startProduct")
	private Integer startProduct;
	@Column(name="price")
	private Double price;
	@Column(name="sale")
	private Integer sale;
	@Column(name="description")
	private Serializable description;
	@Column (name ="timeCreate")
	private Date timeCreate;
	@Column (name ="trademark")
	private Serializable trademark;

	public Product() {
	}

	public Product(Serializable nameProduct, Integer startProduct, Double price, Integer sale, Serializable description,
			Date timeCreate, Serializable trademark) {
		this.nameProduct = nameProduct;
		this.startProduct = startProduct;
		this.price = price;
		this.sale = sale;
		this.description = description;
		this.timeCreate = timeCreate;
		this.trademark = trademark;
	}

	public Integer getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(Integer idProduct) {
		this.idProduct = idProduct;
	}

	public Serializable getNameProduct() {
		return this.nameProduct;
	}

	public void setNameProduct(Serializable nameProduct) {
		this.nameProduct = nameProduct;
	}

	public Integer getStartProduct() {
		return this.startProduct;
	}

	public void setStartProduct(Integer startProduct) {
		this.startProduct = startProduct;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Integer getSale() {
		return this.sale;
	}

	public void setSale(Integer sale) {
		this.sale = sale;
	}

	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	public Date getTimeCreate() {
		return this.timeCreate;
	}

	public void setTimeCreate(Date timeCreate) {
		this.timeCreate = timeCreate;
	}

	public Serializable getTrademark() {
		return this.trademark;
	}

	public void setTrademark(Serializable trademark) {
		this.trademark = trademark;
	}

}
