package Entity;
// Generated Mar 22, 2024, 9:28:17 AM by Hibernate Tools 5.6.15.Final

/**
 * Wishlist generated by hbm2java
 */
public class Wishlist implements java.io.Serializable {

	private Integer idWishlist;
	private Account account;

	public Wishlist() {
	}

	public Wishlist(Account account) {
		this.account = account;
	}

	public Integer getIdWishlist() {
		return this.idWishlist;
	}

	public void setIdWishlist(Integer idWishlist) {
		this.idWishlist = idWishlist;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

}
